##  Plugin Information  ##
name: CraftIRCBridge
main: syam.CraftIRCBridge.CraftIRCBridge
version: 0.1
description: Linking CraftIRC and Herochat for SakuraServer
website: http://sakura-server.net/
depend: [LunaChat, CraftIRC]
##  Original Author     ##
author: syamn
authors: [syamn, ucchy]
